# https://taskfile.dev

version: "3"

env:
  HOME:
    sh: echo $HOME

vars:
  SRC_DIR: src/grafanarama
  SRC_MODEL: jsonschema
  VERSION: 10.4.0
  VERSION_STRING: "v{{ .VERSION }}"
  GRAFANA_VERSION: '{{ or (env "GRAFANA_VERSION") "12.3.0" }}'
  VENV: venv
  SCOPE: schemas
  INPUT_FILE_TYPE: auto
  OUTPUT_MODEL_TYPE: pydantic_v2.BaseModel
  GROK_REPO: '{{ joinPath .HOME "dev/grok" }}'
  GROK_SCHEMA_ROOT: "{{ joinPath .GROK_REPO .SRC_MODEL .VERSION_STRING }}"
  GRAFANA_API_KEY: '{{ env "GRAFANA_API_KEY" }}'
  GRAFANA_USER: '{{ env "GRAFANA_USER" }}'
  GRAFANA_PASSWORD: '{{ env "GRAFANA_PASSWORD" }}'
  GRAFANA_HOST: '{{ env "GRAFANA_HOST" }}'
  GRAFANA_PORT: '{{ env "GRAFANA_PORT" }}'
  
tasks:
  venv:run:
    desc: Run a command inside the venv
    preconditions:
      - test -d {{ .VENV }}
      - test -f "{{ .VENV }}/bin/activate"
    cmds:
      - VIRTUAL_ENV={{.VENV}} PATH="{{.VENV}}/bin${PATH:+:${PATH}}" {{.CLI_ARGS}}

  pip3:install:
    desc: Install or update a package
    cmds:
      - task venv:run -- pip3 install {{.CLI_ARGS}} {{ .PACKAGE }}

  python3:run:
    desc: Run a Python module inside the venv
    cmds:
      - task venv:run -- python3 -m {{ .MODULE }} {{ .CLI_ARGS }}

  tox:run:
    desc: Run tox tests
    cmds:
      - task venv:run -- tox run

  install-xcode-cli:
    desc: Install Xcode Command Line Tools (macOS only)
    status:
      - test -d /Library/Developer/CommandLineTools
      - test -f /Library/Developer/CommandLineTools/usr/bin/git
    cmds:
      - xcode-select --install

  install-poetry:
    desc: Install Poetry package manager
    deps:
      - install-venv
    preconditions:
      - task venv:run -- which pip3
      - task venv:run -- pip3 show setuptools
    status:
      - task venv:run -- which poetry
    cmds:
      - task: pip3:install
        vars: { PACKAGE: "poetry" }

  poetry:install:
    desc: Install dependencies from poetry.lock
    deps:
      - install-poetry
    cmds:
      - task venv:run -- poetry install

  poetry:update:
    desc: Update dependencies using Poetry
    deps:
      - install-poetry
    cmds:
      - task venv:run -- poetry update

  install-venv:
    desc: Create Python virtual environment
    status:
      - test -d {{ .VENV }}
      - test -f "{{ .VENV }}/bin/activate"
    cmds:
      - task: python3:run
        vars: { MODULE: "venv", CLI_ARGS: "{{ .VENV }}" }

  install-*:
    vars:
      PACKAGE: "{{ index .MATCH 0 }}"
    status:
      - task venv:run -- pip3 show {{ .PACKAGE }}
    cmds:
      - task pip3:install -- {{ .CLI_ARGS }} {{ .PACKAGE }}

  update-pip3:
    desc: Update pip to latest version
    preconditions:
      - task venv:run -- which pip3
    cmds:
      - task: python3:run
        vars: { MODULE: "pip", CLI_ARGS: "install --upgrade pip" }

  update-*:
    vars:
      PACKAGE: "{{ index .MATCH 0 }}"
    deps: ["install-{{ .PACKAGE }}"]
    preconditions:
      - task venv:run -- pip3 show {{ .PACKAGE }}
    cmds:
      - task pip3:install -- -U {{ .PACKAGE }}

  mkdirs-core:
    desc: Create core directory structure
    status:
      - test -d grafanarama/core
    cmds:
      - mkdir -p grafanarama/core

  mkdirs-composable:
    desc: Create composable directory structure
    status:
      - test -d grafanarama/composable/panelcfg
      - test -d grafanarama/composable/dataquery
    cmds:
      - mkdir -p grafanarama/composable/panelcfg
      - mkdir -p grafanarama/composable/dataquery

  init-core:
    desc: Initialize core __init__.py files
    status:
      - test -f grafanarama/__init__.py
      - test -f grafanarama/core/__init__.py
    cmds:
      - touch grafanarama/__init__.py
      - touch grafanarama/core/__init__.py

  init-composable:
    desc: Initialize composable __init__.py files
    status:
      - test -f grafanarama/__init__.py
      - test -f grafanarama/composable/__init__.py
      - test -f grafanarama/composable/panelcfg/__init__.py
      - test -f grafanarama/composable/dataquery/__init__.py
    cmds:
      - touch grafanarama/__init__.py
      - touch grafanarama/composable/__init__.py
      - touch grafanarama/composable/panelcfg/__init__.py
      - touch grafanarama/composable/dataquery/__init__.py
  
  build-kinds:
    desc: Build all code-generated kinds (core and composable)
    cmds:
      - task: build-core
      - task: build-composable

  build-core:
    desc: Build core code-generated models
    deps: [mkdirs-core, init-core]
    vars:
      KIND: core
      KIND_PATH: "kinds/{{ .KIND }}"
    sources:
      - '{{ joinPath .GROK_SCHEMA_ROOT .KIND_PATH "/*/x/*.json" }}'
    generates:
      - "{{ .SRC_DIR }}/{{ .KIND }}/*/__init__.py"
      - "{{ .SRC_DIR }}/{{ .KIND }}/*/status.py"
    cmds:
      - for: sources
        vars:
          FILE: "{{ .ITEM }}"
        task: run-codegen-core

  build-composable:
    desc: Build composable code-generated models
    deps: [mkdirs-composable, init-composable]
    vars:
      KIND: composable
      KIND_PATH: "kinds/{{ .KIND }}"
    sources:
      - '{{ joinPath .GROK_SCHEMA_ROOT .KIND_PATH "/*/dataquery/x/*.json" }}'
      - '{{ joinPath .GROK_SCHEMA_ROOT .KIND_PATH "/*/panelcfg/x/*.json" }}'
    generates:
      - "{{ .SRC_DIR }}/{{ .KIND }}/*/panelcfg/__init__.py"
      - "{{ .SRC_DIR }}/{{ .KIND }}/*/panelcfg/status.py"
      - "{{ .SRC_DIR }}/{{ .KIND }}/*/dataquery/__init__.py"
      - "{{ .SRC_DIR }}/{{ .KIND }}/*/dataquery/status.py"
    cmds:
      - for: sources
        vars:
          FILE: "{{ .ITEM }}"
        task: run-codegen-composable

  run-codegen-core:
    vars:
      KIND: core
      SRC_FILE: "{{ base .FILE }}"
      X_DIR: "{{ dir .FILE }}"
      OBJECT_DIR: "{{ dir .X_DIR }}"
      OBJECT: "{{ base .OBJECT_DIR }}"
      DST_DIR: "grafanarama/{{ .KIND }}/{{ .OBJECT }}"
      INPUT_FILE: "{{ joinPath .GROK_REPO .FILE }}"
      OUTPUT_FILE: "{{ .DST_DIR }}/{{ .OBJECT }}.py"
    cmds:
      - task venv:run -- datamodel-codegen --input-file-type {{ .INPUT_FILE_TYPE}} --input {{ .INPUT_FILE }} --output-model-type {{ .OUTPUT_MODEL_TYPE }} --output {{ .DST_DIR }}

  run-codegen-composable:
    vars:
      KIND: composable
      SRC_FILE: "{{ base .FILE }}"
      X_DIR: "{{ dir .FILE }}"
      OBJECT_TYPE_DIR: "{{ dir .X_DIR }}"
      OBJECT_TYPE: "{{ base .OBJECT_TYPE_DIR }}"
      OBJECT_DIR: "{{ dir .OBJECT_TYPE_DIR }}"
      OBJECT: "{{ base .OBJECT_DIR }}"
      DST_DIR: "grafanarama/{{ .KIND }}/{{ .OBJECT_TYPE }}/{{ .OBJECT }}"
      INPUT_FILE: "{{ joinPath .GROK_REPO .FILE }}"
      OUTPUT_FILE: "{{ .DST_DIR }}/{{ .OBJECT }}.py"
    cmds:
      - task venv:run -- datamodel-codegen --input-file-type {{ .INPUT_FILE_TYPE}} --input {{ .INPUT_FILE }} --output-model-type {{ .OUTPUT_MODEL_TYPE }} --output {{ .DST_DIR }}

  tox:run-*:
    vars:
      SUB: "{{ index .MATCH 0 }}"
    cmds:
      - task venv:run -- tox run -e {{ .SUB }}

  grafana:up:
    desc: Start Grafana server (uses GRAFANA_VERSION from Taskfile vars or env var)
    cmds:
      - GRAFANA_VERSION={{.GRAFANA_VERSION}} docker compose up -d

  grafana:down:
    desc: Stop Grafana server
    cmds:
      - docker compose down

  grafana:logs:
    desc: Show Grafana server logs
    cmds:
      - docker compose logs -f grafana

  grafana:restart:
    desc: Restart Grafana server with optional version update
    cmds:
      - task: grafana:down
      - task: grafana:up

  grafana:version:
    desc: Show current Grafana version
    cmds:
      - |
        echo "Grafana version: {{.GRAFANA_VERSION}}"

  grafana:status:
    desc: Show Grafana container status
    cmds:
      - docker compose ps grafana

  grafana:shell:
    desc: Open a shell in the Grafana container
    cmds:
      - docker compose exec grafana /bin/sh
