# generated by datamodel-codegen:
#   filename:  publicdashboard_types_gen.json
#   timestamp: 2024-03-23T05:19:30+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field

from . import status


class FieldKubeObjectMetadata(BaseModel):
    uid: str
    creationTimestamp: AwareDatetime
    deletionTimestamp: Optional[AwareDatetime] = None
    finalizers: List[str]
    resourceVersion: str
    labels: Dict[str, str]


class Metadata(FieldKubeObjectMetadata):
    updateTimestamp: AwareDatetime
    createdBy: str
    updatedBy: str
    extraFields: Dict[str, Any] = Field(
        ...,
        description='extraFields is reserved for any fields that are pulled from the API server metadata but do not have concrete fields in the CUE metadata',
    )


class Spec(BaseModel):
    uid: str = Field(..., description='Unique public dashboard identifier')
    dashboardUid: str = Field(
        ...,
        description='Dashboard unique identifier referenced by this public dashboard',
    )
    accessToken: Optional[str] = Field(None, description='Unique public access token')
    isEnabled: bool = Field(
        ..., description='Flag that indicates if the public dashboard is enabled'
    )
    annotationsEnabled: bool = Field(
        ..., description='Flag that indicates if annotations are enabled'
    )
    timeSelectionEnabled: bool = Field(
        ..., description='Flag that indicates if the time range picker is enabled'
    )


class Status(BaseModel):
    operatorStates: Optional[Dict[str, status.OperatorState]] = Field(
        None,
        description='operatorStates is a map of operator ID to operator state evaluations.\nAny operator which consumes this kind SHOULD add its state evaluation information to this field.',
    )
    additionalFields: Optional[Dict[str, Any]] = Field(
        None, description='additionalFields is reserved for future use'
    )


class Publicdashboard(BaseModel):
    metadata: Metadata = Field(
        ...,
        description='metadata contains embedded CommonMetadata and can be extended with custom string fields\nTODO: use CommonMetadata instead of redefining here; currently needs to be defined here\nwithout external reference as using the CommonMetadata reference breaks thema codegen.',
    )
    spec: Spec
    status: Status
