# generated by datamodel-codegen:
#   filename:  librarypanel_types_gen.json
#   timestamp: 2024-03-23T05:19:28+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from . import status


class LibraryElementDTOMetaUser(BaseModel):
    id: int
    name: str
    avatarUrl: str


class FieldKubeObjectMetadata(BaseModel):
    uid: str
    creationTimestamp: AwareDatetime
    deletionTimestamp: Optional[AwareDatetime] = None
    finalizers: List[str]
    resourceVersion: str
    labels: Dict[str, str]


class Metadata(FieldKubeObjectMetadata):
    updateTimestamp: AwareDatetime
    createdBy: str
    updatedBy: str
    extraFields: Dict[str, Any] = Field(
        ...,
        description='extraFields is reserved for any fields that are pulled from the API server metadata but do not have concrete fields in the CUE metadata',
    )


class LibraryElementDTOMeta(BaseModel):
    folderName: str
    folderUid: str
    connectedDashboards: int
    created: AwareDatetime
    updated: AwareDatetime
    createdBy: LibraryElementDTOMetaUser
    updatedBy: LibraryElementDTOMetaUser


class Spec(BaseModel):
    folderUid: Optional[str] = Field(None, description='Folder UID')
    uid: str = Field(..., description='Library element UID')
    name: constr(min_length=1) = Field(
        ..., description='Panel name (also saved in the model)'
    )
    description: Optional[str] = Field(None, description='Panel description')
    type: constr(min_length=1) = Field(
        ..., description='The panel type (from inside the model)'
    )
    schemaVersion: Optional[conint(ge=0, le=65535)] = Field(
        None, description='Dashboard version when this was saved (zero if unknown)'
    )
    version: int = Field(
        ...,
        description='panel version, incremented each time the dashboard is updated.',
    )
    model: Dict[str, Any] = Field(
        ...,
        description="TODO: should be the same panel schema defined in dashboard\nTypescript: Omit<Panel, 'gridPos' | 'id' | 'libraryPanel'>;",
    )
    meta: Optional[LibraryElementDTOMeta] = None


class Status(BaseModel):
    operatorStates: Optional[Dict[str, status.OperatorState]] = Field(
        None,
        description='operatorStates is a map of operator ID to operator state evaluations.\nAny operator which consumes this kind SHOULD add its state evaluation information to this field.',
    )
    additionalFields: Optional[Dict[str, Any]] = Field(
        None, description='additionalFields is reserved for future use'
    )


class Librarypanel(BaseModel):
    metadata: Metadata = Field(
        ...,
        description='metadata contains embedded CommonMetadata and can be extended with custom string fields\nTODO: use CommonMetadata instead of redefining here; currently needs to be defined here\nwithout external reference as using the CommonMetadata reference breaks thema codegen.',
    )
    spec: Spec
    status: Status
