# generated by datamodel-codegen:
#   filename:  rolebinding_types_gen.json
#   timestamp: 2024-03-23T05:19:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field

from . import status


class Kind(Enum):
    BuiltinRole = 'BuiltinRole'


class Name(Enum):
    viewer = 'viewer'
    editor = 'editor'
    admin = 'admin'


class BuiltinRoleRef(BaseModel):
    kind: Kind
    name: Name


class Kind1(Enum):
    Role = 'Role'


class CustomRoleRef(BaseModel):
    kind: Kind1
    name: str


class Kind2(Enum):
    Team = 'Team'
    User = 'User'


class RoleBindingSubject(BaseModel):
    kind: Kind2
    name: str = Field(..., description='The team/user identifier name')


class FieldKubeObjectMetadata(BaseModel):
    uid: str
    creationTimestamp: AwareDatetime
    deletionTimestamp: Optional[AwareDatetime] = None
    finalizers: List[str]
    resourceVersion: str
    labels: Dict[str, str]


class Metadata(FieldKubeObjectMetadata):
    updateTimestamp: AwareDatetime
    createdBy: str
    updatedBy: str
    extraFields: Dict[str, Any] = Field(
        ...,
        description='extraFields is reserved for any fields that are pulled from the API server metadata but do not have concrete fields in the CUE metadata',
    )


class Spec(BaseModel):
    role: Union[BuiltinRoleRef, CustomRoleRef] = Field(
        ..., description='The role we are discussing'
    )
    subject: RoleBindingSubject


class Status(BaseModel):
    operatorStates: Optional[Dict[str, status.OperatorState]] = Field(
        None,
        description='operatorStates is a map of operator ID to operator state evaluations.\nAny operator which consumes this kind SHOULD add its state evaluation information to this field.',
    )
    additionalFields: Optional[Dict[str, Any]] = Field(
        None, description='additionalFields is reserved for future use'
    )


class Rolebinding(BaseModel):
    metadata: Metadata = Field(
        ...,
        description='metadata contains embedded CommonMetadata and can be extended with custom string fields\nTODO: use CommonMetadata instead of redefining here; currently needs to be defined here\nwithout external reference as using the CommonMetadata reference breaks thema codegen.',
    )
    spec: Spec
    status: Status
