# generated by datamodel-codegen:
#   filename:  accesspolicy_types_gen.json
#   timestamp: 2024-03-23T05:19:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field

from . import status


class Kind(Enum):
    field_ = '*'


class Verb(Enum):
    field_ = '*'
    none = 'none'


class AccessRule(BaseModel):
    kind: Union[Kind, str] = Field(
        ..., description='The kind this rule applies to (dashboards, alert, etc)'
    )
    verb: Union[Verb, str] = Field(
        ...,
        description='READ, WRITE, CREATE, DELETE, ...\nshould move to k8s style verbs like: "get", "list", "watch", "create", "update", "patch", "delete"',
    )
    target: Optional[str] = Field(
        None,
        description='Specific sub-elements like "alert.rules" or "dashboard.permissions"????',
    )


class ResourceRef(BaseModel):
    kind: str
    name: str


class Kind1(Enum):
    Role = 'Role'
    BuiltinRole = 'BuiltinRole'
    Team = 'Team'
    User = 'User'


class RoleRef(BaseModel):
    kind: Kind1 = Field(
        ...,
        description='Policies can apply to roles, teams, or users\nApplying policies to individual users is supported, but discouraged',
    )
    name: str
    xname: str


class FieldKubeObjectMetadata(BaseModel):
    uid: str
    creationTimestamp: AwareDatetime
    deletionTimestamp: Optional[AwareDatetime] = None
    finalizers: List[str]
    resourceVersion: str
    labels: Dict[str, str]


class Metadata(FieldKubeObjectMetadata):
    updateTimestamp: AwareDatetime
    createdBy: str
    updatedBy: str
    extraFields: Dict[str, Any] = Field(
        ...,
        description='extraFields is reserved for any fields that are pulled from the API server metadata but do not have concrete fields in the CUE metadata',
    )


class Spec(BaseModel):
    scope: ResourceRef
    role: RoleRef
    rules: List[AccessRule] = Field(
        ...,
        description='The set of rules to apply.  Note that * is required to modify\naccess policy rules, and that "none" will reject all actions',
    )


class Status(BaseModel):
    operatorStates: Optional[Dict[str, status.OperatorState]] = Field(
        None,
        description='operatorStates is a map of operator ID to operator state evaluations.\nAny operator which consumes this kind SHOULD add its state evaluation information to this field.',
    )
    additionalFields: Optional[Dict[str, Any]] = Field(
        None, description='additionalFields is reserved for future use'
    )


class Accesspolicy(BaseModel):
    metadata: Metadata = Field(
        ...,
        description='metadata contains embedded CommonMetadata and can be extended with custom string fields\nTODO: use CommonMetadata instead of redefining here; currently needs to be defined here\nwithout external reference as using the CommonMetadata reference breaks thema codegen.',
    )
    spec: Spec
    status: Status
