# generated by datamodel-codegen:
#   filename:  preferences_types_gen.json
#   timestamp: 2024-03-23T05:19:29+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field

from . import status


class CookiePreferences(BaseModel):
    analytics: Optional[Dict[str, Any]] = None
    performance: Optional[Dict[str, Any]] = None
    functional: Optional[Dict[str, Any]] = None


class QueryHistoryPreference(BaseModel):
    homeTab: Optional[str] = Field(
        None, description="one of: '' | 'query' | 'starred';"
    )


class FieldKubeObjectMetadata(BaseModel):
    uid: str
    creationTimestamp: AwareDatetime
    deletionTimestamp: Optional[AwareDatetime] = None
    finalizers: List[str]
    resourceVersion: str
    labels: Dict[str, str]


class Metadata(FieldKubeObjectMetadata):
    updateTimestamp: AwareDatetime
    createdBy: str
    updatedBy: str
    extraFields: Dict[str, Any] = Field(
        ...,
        description='extraFields is reserved for any fields that are pulled from the API server metadata but do not have concrete fields in the CUE metadata',
    )


class Spec(BaseModel):
    homeDashboardUID: Optional[str] = Field(
        None, description='UID for the home dashboard'
    )
    timezone: Optional[str] = Field(
        None,
        description='The timezone selection\nTODO: this should use the timezone defined in common',
    )
    weekStart: Optional[str] = Field(
        None, description='day of the week (sunday, monday, etc)'
    )
    theme: Optional[str] = Field(None, description='light, dark, empty is default')
    language: Optional[str] = Field(None, description='Selected language (beta)')
    queryHistory: Optional[QueryHistoryPreference] = None
    cookiePreferences: Optional[CookiePreferences] = None


class Status(BaseModel):
    operatorStates: Optional[Dict[str, status.OperatorState]] = Field(
        None,
        description='operatorStates is a map of operator ID to operator state evaluations.\nAny operator which consumes this kind SHOULD add its state evaluation information to this field.',
    )
    additionalFields: Optional[Dict[str, Any]] = Field(
        None, description='additionalFields is reserved for future use'
    )


class Preferences(BaseModel):
    metadata: Metadata = Field(
        ...,
        description='metadata contains embedded CommonMetadata and can be extended with custom string fields\nTODO: use CommonMetadata instead of redefining here; currently needs to be defined here\nwithout external reference as using the CommonMetadata reference breaks thema codegen.',
    )
    spec: Spec = Field(
        ...,
        description='Spec defines user, team or org Grafana preferences\nswagger:model Preferences',
    )
    status: Status
